<template>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>Website © 2019 KunoichiZ</p>
      <p>Website generated by <a href="https://nuxtjs.org/">Nuxt.js</a></p>
    </div>
  </footer>
</template>

<style scoped>

</style>